title: Veer Thiara
description: Portfolio, project documentation, and learning journey
remote_theme: just-the-docs/just-the-docs

url: https://veerthiara.github.io

color_scheme: dark
search_enabled: true

aux_links:
  GitHub:
    - https://github.com/veerthiara

nav_sort: case_insensitive
